name: pull_flutter
description: Flutter frontend for Pull Dating
publish_to: 'none'

version: 1.0.0+1

environment:
  flutter: ">=3.0.1 <4.0.0"
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.8
  flutter_hooks: ^0.18.4
  hooks_riverpod: ^2.0.0-dev.8
  pull_common:
    path: ../pull_common
  isar_flutter_libs: 2.5.0
  go_router: ^3.1.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  google_fonts: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
